<?php

$pkg = array();

// $NAME is generated by the getName() function
// in `bob_config.php`.
$pkg['name'] = $NAME;

$pkg['require'] = array(
    'php' => '>=5.3.2',
    'symfony/process' => '>=2.0.0,<2.1.0dev'
);

$pkg['autoload'] = array(
    'psr-0' => array(
        'MetaTemplate' => 'lib/'
    )
);

$pkg['description'] = "Templating solution with adapters to many engines";
$pkg['keywords']    = array('templating');
$pkg['license']     = "MIT";
$pkg['homepage']    = "https://github.com/CHH/MetaTemplate";

// These get computed in the `bob_config.php`
if ($VERSION)     $pkg['version'] = $VERSION;
if ($AUTHORS)     $pkg['authors'] = $AUTHORS;

// DO NOT REMOVE THIS
return $pkg;
